[General]
__userfile__=true
backlightIdleness=0
backlightIdlenessOnBatteryDischarging=true
disableIdlenessWhenFullscreen=true
enableBatteryWatcher=false
enableIdlenessBacklightWatcher=false
enableIdlenessWatcher=true
enableLidWatcher=false
idlenessACAction=3
idlenessACTime=@Variant(\0\0\0\xf\0*\x1d@)
idlenessBatteryAction=3
idlenessBatteryTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessTime=@Variant(\0\0\0\xf\0\0\x3\xe8)
runCheckLevel=1
